//go:build !ignore_autogenerated

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package node_scale_adjuster

import (
	"github.com/NVIDIA/KAI-scheduler/pkg/apis/kai/v1/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Args) DeepCopyInto(out *Args) {
	*out = *in
	if in.ScalingPodImage != nil {
		in, out := &in.ScalingPodImage, &out.ScalingPodImage
		*out = new(common.Image)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeScaleNamespace != nil {
		in, out := &in.NodeScaleNamespace, &out.NodeScaleNamespace
		*out = new(string)
		**out = **in
	}
	if in.NodeScaleServiceAccount != nil {
		in, out := &in.NodeScaleServiceAccount, &out.NodeScaleServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.GPUMemoryToFractionRatio != nil {
		in, out := &in.GPUMemoryToFractionRatio, &out.GPUMemoryToFractionRatio
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Args.
func (in *Args) DeepCopy() *Args {
	if in == nil {
		return nil
	}
	out := new(Args)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeScaleAdjuster) DeepCopyInto(out *NodeScaleAdjuster) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(common.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = new(Args)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeScaleAdjuster.
func (in *NodeScaleAdjuster) DeepCopy() *NodeScaleAdjuster {
	if in == nil {
		return nil
	}
	out := new(NodeScaleAdjuster)
	in.DeepCopyInto(out)
	return out
}
