# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queuecontroller
rules:
- apiGroups:
  - scheduling.run.ai
  resources:
  - podgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.run.ai
  resources:
  - queues
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.run.ai
  resources:
  - queues/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.run.ai
  resources:
  - queues/status
  verbs:
  - get
  - patch
  - update
