# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: scheduler
      containers:
        - name: scheduler
          image: "{{ .Values.global.registry }}/{{ .Values.scheduler.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          args:
            - "--scheduler-conf=/etc/config/config.yaml"
            - "--namespace={{ .Release.Namespace }}"
            - "--resource-reservation-app-label={{ .Values.global.resourceReservation.appLabel }}"
          {{- if .Values.scheduler.additionalArgs }}
            {{- toYaml .Values.scheduler.additionalArgs | nindent 12 }}
          {{- end }}
          {{- if .Values.scheduler.resources }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.scheduler.ports.metricsPort }}
          volumeMounts:
            - name: config
              subPath: "config.yaml"
              mountPath: "/etc/config/config.yaml"
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: scheduler-config
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}