# Copyright 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: DCO
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  dco-pull-request:
    name: DCO
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run python DCO check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -U dco-check
          dco-check --verbose

  dco-merge-queue:
    name: DCO
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - name: Skip DCO for merge queue
        run: |
          echo "DCO was already validated before entering merge queue"
